 -- 1.
-- 보너스 포함 연봉 순위
SELECT  EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, 순위
FROM (SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, 
            (SALARY +SALARY*NVL(BONUS,0)) *12, RANK() OVER (ORDER BY(SALARY +SALARY*NVL(BONUS,0)) DESC) "순위"
            FROM EMPLOYEE E, DEPARTMENT D, JOB J
            WHERE E.DEPT_CODE = D.DEPT_ID
            AND E.JOB_CODE = J.JOB_CODE)
WHERE ROWNUM <=5;


-- 2.
-- 전체 급여 총합의 20%
SELECT SUM(SALARY)*0.2
FROM EMPLOYEE;

SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
GROUP BY DEPT_TITLE, DEPT_CODE
HAVING SUM(SALARY)> ANY (SELECT SUM(SALARY)*0.2
                                    FROM EMPLOYEE) ;


-- 3.
WITH SAL AS (SELECT SALARY
FROM EMPLOYEE)
SELECT SUM(SALARY), AVG(SALARY)
FROM SAL;


