DROP TABLE RESTAURANT;
DROP TABLE LOCATION;
DROP TABLE FOOD;

DROP SEQUENCE SEQ_RESTAURANT;
DROP SEQUENCE SEQ_LOCATION;    
DROP SEQUENCE SEQ_FOOD;


CREATE TABLE RESTAURANT(
    RES_CODE NUMBER,
    RES_NAME VARCHAR2(200) NOT NULL,
    RES_ADDR VARCHAR2(200) NOT NULL,
    RES_PHONE VARCHAR2(200) NOT NULL,
    RES_OPEN_HOUR VARCHAR2(100),  
    RES_CLOSE VARCHAR2(100),  
    RES_DESC VARCHAR2(500),
    LOCAL_CODE NUMBER,
    FOOD_CODE NUMBER
);

CREATE TABLE LOCATION(
    LOCAL_CODE NUMBER,
    LOCAL_NAME VARCHAR2(200) NOT NULL
);

CREATE TABLE FOOD(
    FOOD_CODE NUMBER,
    FOOD_TYPE VARCHAR2(100) NOT NULL
);

-- PK
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_RES_CODE_PK PRIMARY KEY(RES_CODE);
ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_LOCAL_CODE_PK PRIMARY KEY(LOCAL_CODE);
ALTER TABLE FOOD ADD CONSTRAINT FOOD_FOOD_CODE_PK PRIMARY KEY(FOOD_CODE);

-- FK
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_USER_CODE_FK FOREIGN KEY(USER_CODE) REFERENCES MEMBER;
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_LOCAL_CODE_FK FOREIGN KEY(LOCAL_CODE) REFERENCES LOCATION;
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_FOOD_CODE_FK FOREIGN KEY(FOOD_CODE) REFERENCES FOOD;


-- SEQ
CREATE SEQUENCE SEQ_RESTAURANT;
CREATE SEQUENCE SEQ_LOCATION;    
CREATE SEQUENCE SEQ_FOOD;


-- INSERT


INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '김밥천국', '서울 강남구', '02-111-1111');
INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '나이스샤워', '서울 강남구', '02-222-2222');
INSERT INTO RESTAURANT(RES_CODE, RES_NAME, RES_ADDR, RES_PHONE) VALUES(SEQ_RESTAURANT.NEXTVAL, '김남완초밥', '서울 강남구', '02-333-3333');


INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '서울');
INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '경기');
INSERT INTO LOCATION(LOCAL_CODE, LOCAL_NAME) VALUES(SEQ_LOCATION.NEXTVAL, '인천');

INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '한식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '양식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '일식');
INSERT INTO FOOD(FOOD_CODE, FOOD_TYPE) VALUES(SEQ_FOOD.NEXTVAL, '중식');




-- SELECT
SELECT * FROM RESTAURANT;
SELECT * FROM LOCATION;
SELECT * FROM FOOD;


