-- 1.
CREATE TABLE TB_CATEGORY(
    CATEGORY_NAME VARCHAR2(10),
    CATEGORY_USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. 
CREATE TABLE TB_CLASS_TYPE(
    CLASS_TYPE_NO VARCHAR2(5) PRIMARY KEY,
    CLASS_TYPE_NAME VARCHAR2(10)
);