--1. 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3.
SELECT
  PROFESSOR_NAME AS "교수이름",
  EXTRACT(YEAR FROM SYSDATE) - TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1, 2) + 1900) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2,3) 이름
FROM TB_PROFESSOR;


--5. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - TO_NUMBER(SUBSTR(STUDENT_SSN,1,2)+1900) > 19;


--6.
SELECT TO_CHAR(TO_DATE('20201225','YY/MM/DD'), 'DAY')
FROM DUAL;

--7.
SELECT 
    TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),  'YYYY"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),  'YYYY"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY"년" MM"월" DD"일"'),
    TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9.
SELECT ROUND(SUM(POINT)/COUNT(CLASS_NO),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO 학과번호, COUNT(STUDENT_NO) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11. 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

/*
--12.
SELECT TO_CHAR(TERM_NO, 'YYYY') 년도, ROUND(SUM(POINT)/COUNT(TERM_NO),1) "년도 별 평점"
FROM TB_GRADE
GROUP BY TERM_NO
WHERE STUDENT_NO = 'A112113';
*/

--13.
SELECT 
    DEPARTMENT_NO 학과코드명, 
    COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y' 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;  --다시(Y가 아닌경우도 셀수있어야함)





